site_name: Dungeon Crawler Earth
theme:
  name: material
  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
nav:
  - Dungeon Crawler Earth: 'index.md'
  - Combat Quick Reference: 'Combat Quick Reference.md'
  - Abilities:
    - Abilities: 'Abilities.md'
    - Banes:
      - index: 'Banes.md'
      - Blinded: 'Blinded.md'
      - Charmed: 'Charmed.md'
      - Deafened: 'Deafened.md'
      - Death: 'Death.md'
      - Demoralized: 'Demoralized.md'
      - Disarmed: 'Disarmed.md'
      - Dominated: 'Dominated.md'
      - Fatigued: 'Fatigued.md'
      - Fear: 'Fear.md'
      - Forced Move: 'Forced Move.md'
      - Immobile: 'Immobile.md'
      - Incapacitated: 'Incapacitated.md'
      - Knockdown: 'Knockdown.md'
      - Memory Alteration: 'Memory Alteration.md'
      - Mind Dredge: 'Mind Dredge.md'
      - Nullify: 'Nullify.md'
      - Persistent Damage: 'Persistent Damage.md'
      - Phantasm: 'Phantasm.md'
      - Polymorph: 'Polymorph.md'
      - Provoked: 'Provoked.md'
      - Sickened: 'Sickened.md'
      - Silenced: 'Silenced.md'
      - Slowed: 'Slowed.md'
      - Spying: 'Spying.md'
      - Stunned: 'Stunned.md'
      - Stupefied: 'Stupefied.md'
      - Truthfulness: 'Truthfulness.md'
    - Boons:
      - index: 'Boons.md'
      - Absorb Object: 'Absorb Object.md'
      - Animation: 'Animation.md'
      - Aura: 'Aura.md'
      - Barrier: 'Barrier.md'
      - Blindsight: 'Blindsight.md'
      - Bolster: 'Bolster.md'
      - Concealment: 'Concealment.md'
      - Darkness: 'Darkness.md'
      - Detection: 'Detection.md'
      - Flight: 'Flight.md'
      - Genesis: 'Genesis.md'
      - Haste: 'Haste.md'
      - Heal: 'Heal.md'
      - Insubstantial: 'Insubstantial.md'
      - Invisible: 'Invisible.md'
      - Life Drain: 'Life Drain.md'
      - Light: 'Light.md'
      - Precognition: 'Precognition.md'
      - Reading: 'Reading.md'
      - Regeneration: 'Regeneration.md'
      - Resistance: 'Resistance.md'
      - Restoration: 'Restoration.md'
      - Seeing: 'Seeing.md'
      - Shapeshift: 'Shapeshift.md'
      - Summon Creature: 'Summon Creature.md'
      - Sustenance: 'Sustenance.md'
      - Telekinesis: 'Telekinesis.md'
      - Telepathy: 'Telepathy.md'
      - Teleport: 'Teleport.md'
      - Tongues: 'Tongues.md'
      - Transmutation: 'Transmutation.md'
      - Truesight: 'Truesight.md'
    - Feats:
      - index: 'Feats.md'
      - Alternate Form (I - II): 'Alternate Form (I - II).md'
      - Area Manipulation (I - V): 'Area Manipulation (I - V).md'
      - Armor Mastery (I - II): 'Armor Mastery (I - II).md'
      - Attack Redirection: 'Attack Redirection.md'
      - Attack Specialization (I - IX): 'Attack Specialization (I - IX).md'
      - Attribute Substitution (I - II): 'Attribute Substitution (I - II).md'
      - Bane Focus: 'Bane Focus.md'
      - Battle Trance: 'Battle Trance.md'
      - Battlefield Opportunist (I - V): 'Battlefield Opportunist (I - V).md'
      - Battlefield Punisher: 'Battlefield Punisher.md'
      - Battlefield Retribution: 'Battlefield Retribution.md'
      - Boon Access: 'Boon Access.md'
      - Boon Focus (I - III): 'Boon Focus (I - III).md'
      - Breakfall (I - II): 'Breakfall (I - II).md'
      - Brutal Intimidation: 'Brutal Intimidation.md'
      - Climbing: 'Climbing.md'
      - Combat Follow-through: 'Combat Follow-through.md'
      - Combat Momentum: 'Combat Momentum.md'
      - Companion (I - III): 'Companion (I - III).md'
      - Craft Mundane Item (I - II): 'Craft Mundane Item (I - II).md'
      - Craft Extraordinary Item (I - III): 'Craft Extraordinary Item (I - III).md'
      - Crushing Blow: 'Crushing Blow.md'
      - Death Blow (I - II): 'Death Blow (I - II).md'
      - Deathless Trance: 'Deathless Trance.md'
      - Defensive Mastery: 'Defensive Mastery.md'
      - Defensive Reflexes (I - IX): 'Defensive Reflexes (I - IX).md'
      - Destructive Trance: 'Destructive Trance.md'
      - Diehard: 'Diehard.md'
      - Energy Resistance (I - IV): 'Energy Resistance (I - IV).md'
      - Evasive Footwork: 'Evasive Footwork.md'
      - Extraordinary Defense (I - III): 'Extraordinary Defense (I - III).md'
      - Extraordinary Focus: 'Extraordinary Focus.md'
      - Extraordinary Healing: 'Extraordinary Healing.md'
      - Fast Draw: 'Fast Draw.md'
      - Fast Tracker: 'Fast Tracker.md'
      - Ferocious Minions (I - III): 'Ferocious Minions (I - III).md'
      - Fleet of Foot (I - III): 'Fleet of Foot (I - III).md'
      - Flying: 'Flying.md'
      - Great Leap (I - III): 'Great Leap (I - III).md'
      - Hallucination (I - II): 'Hallucination (I - II).md'
      - Heightened Invocation (I - III): 'Heightened Invocation (I - III).md'
      - Hospitaler: 'Hospitaler.md'
      - Impervious Trance: 'Impervious Trance.md'
      - Indomitable Endurance (I - V): 'Indomitable Endurance (I - V).md'
      - Indomitable Resolve (I - III): 'Indomitable Resolve (I - III).md'
      - Inspiring Champion (I - III): 'Inspiring Champion (I - III).md'
      - Knowledge (I - III): 'Knowledge (I - III).md'
      - Lethal Strike (I - IX): 'Lethal Strike (I - IX).md'
      - Lightning Reflexes (I - V): 'Lightning Reflexes (I - V).md'
      - Longshot: 'Longshot.md'
      - Silencing Strike: 'Silencing Strike.md'
      - Martial Focus: 'Martial Focus.md'
      - Master Tracker: 'Master Tracker.md'
      - Mimic: 'Mimic.md'
      - Multi-Attack Specialist (I - VI): 'Multi-Attack Specialist (I - VI).md'
      - Multi-Bane Specialist: 'Multi-Bane Specialist.md'
      - Multi-Target Attack Specialist (I - V): 'Multi-Target Attack Specialist (I - V).md'
      - Multi-Target Boon Expert: 'Multi-Target Boon Expert.md'
      - Multi-Target Boon Specialist (I - IX): 'Multi-Target Boon Specialist (I - IX).md'
      - Natural Defense (I - III): 'Natural Defense (I - III).md'
      - Overpowering Strike: 'Overpowering Strike.md'
      - Potent Bane: 'Potent Bane.md'
      - Reactionary Trance: 'Reactionary Trance.md'
      - Reckless Attack: 'Reckless Attack.md'
      - Resilient: 'Resilient.md'
      - Sentinel (I - III): 'Sentinel (I - III).md'
      - Skill Specialization (I - V): 'Skill Specialization (I - V).md'
      - Superior Concentration (I - III): 'Superior Concentration (I - III).md'
      - Swimming: 'Swimming.md'
      - Sworn Enemy (I - IX): 'Sworn Enemy (I - IX).md'
      - Tough as Nails (I - II): 'Tough as Nails (I - II).md'
      - Two Weapon Brute: 'Two Weapon Brute.md'
      - Two Weapon Defense: 'Two Weapon Defense.md'
      - Unending Charm: 'Unending Charm.md'
      - Untrackable: 'Untrackable.md'
      - Vicious Strike: 'Vicious Strike.md'
      - Wealthy: 'Wealthy.md'
      - Well-Rounded: 'Well-Rounded.md'
    - Special Attacks: 'Special Attacks.md'
  - Mechanics:
    - Action Roll: 'Action Roll.md'
    - Advantage: 'Advantage.md'
    - Combat: 'Combat.md'
    - Challenge Rating: 'CR.md'
    - Defenses: 'Defenses.md'
    - Finishing Blow: 'Finishing Blow.md'
    - Hit Points: 'Hit Points.md'
    - Initiative: 'Initiative.md'
    - Legend Points: 'Legend Points.md'
    - Power Level: 'Power Level.md'
    - Race: 'Race.md'
    - Rank: 'Rank.md'
    - Reach: 'Reach.md'
    - Turn Actions: 'Turn Actions.md'
  - Attributes:
    - Attributes: 'Attributes.md'
    - Attribute Score: 'Attribute Score.md'
    - Power: 'Power.md'
    - Recovery: 'Recovery.md'
    - Speed: 'Speed.md'
    - Spirit: 'Spirit.md'
  - Items:
    - Armor: 'Armor.md'
    - Carrying Capacity: 'Carrying Capacity.md'
    - Mounts and Vehicles: 'Mounts and Vehicles.md'
    - Special Items: 'Special Items.md'
    - Weapons: 'Weapons.md'
